---
abstract: 'Simple and reliable scoped locking for coarse grained locks.'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>.'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-Lock-RabbitMQ
no_index:
  directory:
    - inc
    - t
requires:
  Devel::GlobalDestruction: 0
  Moose: 0
  Net::RabbitFoot: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://somewhere.com/myproject.git
version: 0.007
